// <auto-generated />
using System;
using DailyTasksApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyTasksApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyTasksApp.Models.DailyTasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GifPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TasksDone")
                        .HasColumnType("int");

                    b.Property<Guid>("WeeklyTasksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyTasksId");

                    b.ToTable("DailyTasks", (string)null);
                });

            modelBuilder.Entity("DailyTasksApp.Models.SingleTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DailyTasksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DailyTasksId");

                    b.ToTable("SingleTasks", (string)null);
                });

            modelBuilder.Entity("DailyTasksApp.Models.WeeklyTasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeeklyTasks", (string)null);
                });

            modelBuilder.Entity("DailyTasksApp.Models.DailyTasks", b =>
                {
                    b.HasOne("DailyTasksApp.Models.WeeklyTasks", "WeeklyTask")
                        .WithMany("DailyTasksList")
                        .HasForeignKey("WeeklyTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyTask");
                });

            modelBuilder.Entity("DailyTasksApp.Models.SingleTask", b =>
                {
                    b.HasOne("DailyTasksApp.Models.DailyTasks", "DailyTask")
                        .WithMany("TaskList")
                        .HasForeignKey("DailyTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyTask");
                });

            modelBuilder.Entity("DailyTasksApp.Models.DailyTasks", b =>
                {
                    b.Navigation("TaskList");
                });

            modelBuilder.Entity("DailyTasksApp.Models.WeeklyTasks", b =>
                {
                    b.Navigation("DailyTasksList");
                });
#pragma warning restore 612, 618
        }
    }
}
